name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Create builder
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kube-pgadmin4-azure:latest
            ghcr.io/${{ github.repository_owner }}/kube-pgadmin4-azure:${{ github.sha }}
          secrets: |
            rhsm_user=${{ secrets.RHSM_USER }}
            rhsm_pass=${{ secrets.RHSM_PASS }}
          build-args: |
            PGADMIN_VERSION=9
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image for CVEs
        uses: anchore/scan-action@v7
        with:
          image: ghcr.io/${{ github.repository_owner }}/kube-pgadmin4-azure:latest
          format: sarif
          output_path: grype-results.sarif
          fail_on: 'HIGH,CRITICAL'
          
      - name: Push Docker image
        uses: docker/build-push-action@v5
        if: success()
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kube-pgadmin4-azure:latest
            ghcr.io/${{ github.repository_owner }}/kube-pgadmin4-azure:${{ github.sha }}
          secrets: |
            rhsm_user=${{ secrets.RHSM_USER }}
            rhsm_pass=${{ secrets.RHSM_PASS }}
          build-args: |
            PGADMIN_VERSION=9
          cache-from: type=gha

      - name: Upload Grype scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'grype-results.sarif'