name: Build, Scan and Push Multi-arch Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-scan:
    name: Build and scan per-platform
    runs-on: ubuntu-latest
    environment: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            suffix: amd64
          - platform: linux/arm64
            suffix: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Create builder
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image for ${{ matrix.platform }} and load
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: |
            kube-pgadmin4-azure:${{ github.sha }}-${{ matrix.suffix }}
          secrets: |
            rhsm_user=${{ secrets.RHSM_USER }}
            rhsm_pass=${{ secrets.RHSM_PASS }}
          build-args: |
            PGADMIN_VERSION=9
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image for CVEs (Anchore/Grype)
        uses: anchore/scan-action@v7
        with:
          image: kube-pgadmin4-azure:${{ github.sha }}-${{ matrix.suffix }}
          fail-build: true
          severity-cutoff: high
          output-format: table,sarif
          output-file: grype-results-${{ matrix.suffix }}

      - name: Print failed CVEs (table)
        if: always()
        run: cat grype-results-${{ matrix.suffix }}.table || echo "No table file found"

      - name: Upload scan results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-results-${{ matrix.suffix }}.sarif
          path: grype-results-${{ matrix.suffix }}.sarif

  push-manifest:
    name: Push multi-arch manifest (only if scans passed)
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: needs.build-and-scan.result == 'success'
    environment: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create builder for push
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push manifest (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kangarookube/kube-pgadmin4-azure:latest
            ghcr.io/kangarookube/kube-pgadmin4-azure:${{ github.sha }}
          secrets: |
            rhsm_user=${{ secrets.RHSM_USER }}
            rhsm_pass=${{ secrets.RHSM_PASS }}
          build-args: |
            PGADMIN_VERSION=9
          cache-from: type=gha

      - name: (Optional) Upload combined scan artifacts
        if: always()
        uses: actions/download-artifact@v4
        with:
          path: ./scan-results

      - name: Upload combined scan results to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: './scan-results'